language: node_js
node_js:
- "10"

services:
- docker

cache:
  directories:
  - node_modules

matrix:
  fast_finish: true

before_install:
- npm install -g npm
- npm install -g release-it greenkeeper-lockfile ganache-cli

before_script:
- greenkeeper-lockfile-update
- ganache-cli > ganache-cli.log &
- sleep 2

script:
- npm run test:cover
- npm run build
- npm run doc

after_script:
- greenkeeper-lockfile-upload

notifications:
  email: false

deploy:
- provider: npm
  email: "devops@oceanprotocol.com"
  api_key: ${NPM_TOKEN}
  skip_cleanup: true
  on:
    tags: true
    condition: $DEPLOY_PACKAGE = true