language: node_js
node_js:
  - "10"

services:
  - docker

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

before_install:
  - npm install -g npm
  - npm install -g codacy-coverage release-it greenkeeper-lockfile

before_script:
  - greenkeeper-lockfile-update
  - git clone https://github.com/oceanprotocol/barge
  - cd barge
  - bash -x start_ocean.sh --latest --no-brizo --no-pleuston --local-spree-node 2>&1 > start_ocean.log &
  - cd ..
  - ./scripts/wait_for_migration_and_extract_keeper_artifacts.sh

script:
  - npm run test:cover
  - npm run report-coverage
  - npm run build
  - npm run doc

after_script:
  - greenkeeper-lockfile-upload

notifications:
  email: false

deploy:
  - provider: npm
    email: "devops@oceanprotocol.com"
    api_key: ${NPM_TOKEN}
    skip_cleanup: true
    on:
      tags: true

